### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Giovanni1085** [inverniz/FDH_SecondarySources#1]
You might want at some point to comment your code a bit! :)
NB if you want me to launch it from a machine or cluster, you should ideally parallelise it or use spark or other means to do multiple queries at the same time on different threads or cores. But be careful of limits. Let me know if you need help here (easiest way is perhaps to use Pathos: https://pypi.python.org/pypi/pathos).

**Comment by inverniz** [comment]
We discussed with the Dandelion team and they kindly upgraded our Dandelion plan for one month so we got a 30x boost in performance, i.e. we can do in a day what we would have done in a month. One condition was to avoid parallel/concurring calls to the api, which are kinda unneeded given the current situation.
The problem remains on how to handle limit. We'll discuss this with you on Wednesday.
